{
 "title": "BT Smart Hub",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connection Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (smarthub_connected)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (smarthub_uptime)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connection Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (smarthub_connection_uptime)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Download Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (smarthub_downloaded_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Upload Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (smarthub_uploaded_bytes)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WAN Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum (rate(smarthub_uploaded_bytes[$__rate_interval])*8)",
     "legendFormat": "Upload"
    },
    {
     "expr": "sum (rate(smarthub_downloaded_bytes[$__rate_interval])*8)",
     "legendFormat": "Download"
    }
   ]
  },
  {
   "title": "WAN Traffic By Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (mac, ip, hostname) (rate(smarthub_lan_downloaded_bytes[$__rate_interval])*8 !=0)",
     "legendFormat": "{{hostname}} {{ip}} downloaded"
    },
    {
     "expr": "sum by (mac, ip, hostname) (-rate(smarthub_lan_uploaded_bytes[$__rate_interval])*8 !=0)",
     "legendFormat": "{{hostname}} {{ip}} uploaded"
    }
   ]
  },
  {
   "title": "Total WAN Download Since Restart",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (mac, ip, hostname) (smarthub_lan_downloaded_bytes)",
     "legendFormat": "{{ip}} {{hostname}} {{mac}}"
    }
   ]
  },
  {
   "title": "Total Upload WAN Since Restart",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (mac, ip, hostname) (smarthub_lan_uploaded_bytes)",
     "legendFormat": "{{ip}} {{hostname}} {{mac}}"
    }
   ]
  }
 ]
}